networks:
  monitoring:
    driver: bridge

volumes:
  prometheus_data:
  grafana_data:

services:
  # Mlflow server
  mlflow:
    image: banibaharihakim/cc
    ports:
      - "5005:5005"
    networks:
      - monitoring
    restart: unless-stopped

  # Prometheus exporter
  prometheus_exporter:
    build:
      context: .
      dockerfile: Dockerfile.exporter
    ports:
      - "8000:8000"
    environment:
      - MLFLOW_URL=http://mlflow:5005
    networks:
      - monitoring
    depends_on:
      - mlflow
    restart: unless-stopped

  # Prometheus
  prometheus:
    image: dhi.io/prometheus:3.12
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    networks:
      - monitoring
    depends_on:
      - prometheus_exporter
    restart: unless-stopped

  # Grafana
  grafana:
    image: dhi.io/grafana:13
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SMTP_ENABLED=true
      - GF_SMTP_HOST=smtp.gmail.com:587
      - GF_SMTP_USER=jbin4502@gmail.com
      - GF_SMTP_PASSWORD=jtxq hotp oskf luck
      - GF_SMTP_FROM_ADDRESS=jbin4502@gmail.com
      - GF_SMTP_FROM_NAME=Grafana
    networks:
      - monitoring
    depends_on:
      - prometheus
    restart: unless-stopped